source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking'
pod 'BDBOAuth1Manager'
pod 'MBProgressHUD', '~> 0.8'
pod 'SWTableViewCell', '~> 0.3.5'
pod 'MZFormSheetController'
pod 'SVPullToRefresh'